### ISSUE TITLE
NDTiff backend to datastore

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/micro-manager#1490]
Working on this now. I've got a preliminary version working, and will update progress here prior to creating a PR.

**Updates to NDTiff**
- [x] Remove the extra `full resolution` directory when not saving in multi-resolution mode, because it's confusing.
- [x] Add in explicit versioning of the format
- [x] Consolidate python reader code into the NDTiff repo and out of pycro-manager
- [x] Signalling new images for custom viewers through both pyramid and regular
- [x] Develop tests for old/new versions, multi-res/non-multi-res, java/python and build in tests as Github actions.
- [x] Update description on NDTiff README
- [x] Get updates to pypi working
- [x] Check appearance of documentation in pycro-manager
- [x] Update micro-manager Ivy and Maven versions
- [x] Simple addition on Readme of how to open them

**TODO on compatibility layer**
- [x] Check that path of saved files isn't creating extra directories
- [x] Test that datasets can be loaded back in as expected
- [x] Display settings

**Performance considerations**
There likely needs to be more investigation as to whether performance overhead is introduced by the 2.0 API converting from `JSONObject` to `Metadata` and back again. Comparisons to fast acquisitions using magellan/pycro-manager would be instructive

**Comment by henrypinkard** [comment]
https://github.com/micro-manager/micro-manager/pull/1496/
